[package]
name = "wasm_send"
version.workspace = true
publish.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64.workspace = true
eyre.workspace = true
reqwest = { version = "0.12.5", features = ["json"] }
serde_json.workspace = true
tokio.workspace = true
